### ISSUE TITLE
Including a list of open-source implementations?

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#116]
Would it be of any benefit to include a list of (high-quality) open-source decoder implementations? Or would this be something too volatile? I'd think of something like this:

- libFLAC (C and C++, BSD-like license)
- ffmpeg (C, GNU LGPL)
- Firefox (C, MPL)
- dr_libs (C. Public Domain/MIT No Attribution)
- Claxon (Rust, Apache 2.0)
- jFLAC (Java, LGPL)

**Comment by retokromer** [comment]
I would include at least a reference implementation which, I presume, is `libFLAC`.

**Comment by SpencerDawkins** [comment]
For @ktmf01 - If you're thinking the list is valuable, but volatile, and the FLAC community is willing to maintain the list, one option is to pick a (stable) place to put the list you're maintaining, and include a pointer to that list in the FLAC specification.

For @retokromer - if there is a stable place to look for libFLAC, you could definitely put a pointer to the reference implementation in the FLAC specification. 

Do those suggestions make sense?

**Comment by mcr** [comment]
One stable place is the github wiki (here).
Another stable place is the new IETF wiki (not yet deployed. Old one was aweful).

**Comment by ValZapod** [comment]
> * ffmpeg

We have some crazy bugs in it. But yes it is more effective than even reference with AVX patches. https://trac.ffmpeg.org/query?status=!closed&keywords=~flac

**Comment by retokromer** [comment]
I actually use the FFmpeg implementation for teaching, but in production we use the libFLAC library inside FFmpeg.

**Comment by wader** [comment]
Hello, i've been working on a tool for inspecting and querying binary files for a while that has quite good FLAC support that might be useful to other, it can be found here https://github.com/wader/fq.
My main uses of it currently is to debug broken media file, decoders, demuxers etc but also do various statistics like packing overhead, extract data for potting and so on.

**Comment by JeromeMartinez** [comment]
> Hello, i've been working on a tool for inspecting and querying binary files for a while that has quite good FLAC support that might be useful to others, it can be found here https://github.com/wader/fq.

Wow, it is huge work. And an alternative to [MediaTrace](https://mediaarea.net/MediaTrace).
(I see that you listed it in related projects :-p)

Test files and a description about what's wrong with them could be added to https://github.com/ietf-wg-cellar/flac-test-files .

***

About a list, it may be useful to have it and volatility is fine in my opinion, it is a base for users. As well as a list on debugging tools.

**Comment by wader** [comment]
> Wow, it is huge work. And an alternative to [MediaTrace](https://mediaarea.net/MediaTrace). (I see that you listed it in related projects :-p)

Thanks for the kind words 😊  and yes it has been lot of work, but also lot of fun and very interesting. But there are many things that feel a bit strange and broken still, i got a lot for free by basing it on the jq language but that also came with many edge cases to figure out :).
I should really try to get some guide and tutorial up how to use it. The expressiveness of jq is very impressive and powerful, for example i used this snippet last month to find false sync frames in FLAC files that ffmpeg reported error for:

```jq
( .frames[]
| . as $f
| tobytesrange[1:]
| scan_toend([0xff,0xf8])
| flac_frame
| select(.header.crc | todescription == "valid")?
| "frame"
, $f
, "false frame"
, (. | d)
)
```
Would show something like this for each false frame: (didn't have any broken files at hand so used `tobytesrange[0:]`)
```
"frame"
      │00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13│0123456789abcdef0123│.frames[0]{}: (flac_frame)
0x0988│                  ff f8 49 18 00 c9                        │      ..I...        │  header{}:
0x0988│                                    52 fe 16 fe 02 fd f2 fd│            R.......│  subframes[0:2]:
0x099c│e9 fd f2 fe 0d fe 37 fe 67 fe 99 fe d9 a3 9b 7b 96 41 83 e6│......7.g......{.A..│
*     │until 0x1bef.6 (4700)                                      │                    │
0x1be4│                                 5e                        │           ^        │  byte_align: 0 (valid)
0x1be4│                                    5e 6f                  │            ^o      │  footer_crc: "5e6f" (raw bits) (valid)
"false frame"
      │00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13│0123456789abcdef0123│.{}: (flac_frame)
      │                                                           │                    │  header{}:
0x0988│                  ff f8                                    │      ..            │    sync: 0b11111111111110 (valid)
0x0988│                     f8                                    │       .            │    reserved0: 0 (valid)
0x0988│                     f8                                    │       .            │    blocking_strategy: "fixed" (0)
0x0988│                        49                                 │        I           │    block_size: 2304 (0b100)
0x0988│                        49                                 │        I           │    sample_rate: 44100 (0b1001)
0x0988│                           18                              │         .          │    channel_assignment: 2 (1) (lr)
0x0988│                           18                              │         .          │    sample_size: 16 (0b100)
0x0988│                           18                              │         .          │    reserved1: 0 (valid)
      │                                                           │                    │    end_of_header{}:
0x0988│                              00                           │          .         │      frame_number: 0
0x0988│                                 c9                        │           .        │    crc: 0xc9 (valid)
... cut ...
```

Would like to thank you too for all the mediaarea work, i use those tools a lot and in combination with fq and also as a reference when developing fq. The more tools the merrier i think!

Sorry for hijacking this issue with a long fq post, if you or someone wants to discuss further let's email and maybe continue in fq repo?

**Comment by ktmf01** [comment]
I've started working on a list of implementation in the github wiki: https://github.com/ietf-wg-cellar/flac-specification/wiki/Implementations

I presume this repository will be kept around after the spec is finished?

**Comment by wader** [comment]
Feel free to include https://github.com/wader/flac.tcl if you want

**Comment by ktmf01** [comment]
Currently the list only contains libraries, but I'll include in when I add a section with tools

**Comment by retokromer** [comment]
>I presume this repository will be kept around after the spec is finished?

It’s what I presume as well.
