### ISSUE TITLE
Frame number reset handling

### ISSUE THREAD

**Issue by wader** [ietf-wg-cellar/flac-specification#127]
Hi, i've encountered a group of flac files (from the same album) that all have the same peculiar behaviour. They all have end-of-header frame number that behaves like this:
- In frame 0 to 2048 the frame number 256 resets back 0
- At frame 2048 the resetting stops and goes from 255 to 2048 and after that seems normal

I can't find anything in the FLAC specification how this should be handled.

The xiph decoder seems to ignore the resets and decodes all the samples. ffmpeg seems to not like it and throws away samples at each reset. Should also note that the files have invalid samples MD5 but i think that is unrelated to this. It's a know issue with the "Switch Plus" flac encoder, for what i can see the frames are fine. I have other switch pro files with invalid MD5 where the frame number does not reset.

Unfortunately i can't share these files because of copyright and i haven't yet been able to generate files with the same behaviour. But here is a session with fq showing the relevant parts and also output from decoding with xiph flac and ffmpeg and then counting number of samples decoded. There is 13692480-13594624 = 97856 samples missing and looking at the output it looks like ffmpeg throws away 3 frames per reset which kind of matches number of resets 97856 / 4096 / 3 = 7.963541666666667.

```
$ fq -o line_bytes=10 -i . <redacted>.flac

# display all metadata
flac> .metadatablocks[] | d
    │00 01 02 03 04 05 06 07 08 09│0123456789│.metadatablocks[0]{}: (flac_metadatablock)
0x00│            00               │    .     │  last_block: false
0x00│            00               │    .     │  type: "streaminfo" (0)
0x00│               00 00 22      │     .."  │  length: 34
0x00│                        10 00│        ..│  minimum_block_size: 4096
0x0a│10 00                        │..        │  maximum_block_size: 4096
0x0a│      00 00 00               │  ...     │  minimum_frame_size: 0
0x0a│               00 00 00      │     ...  │  maximum_frame_size: 0
0x0a│                        0a c4│        ..│  sample_rate: 44100
0x14│42                           │B         │
0x14│42                           │B         │  channels: 2
0x14│42 f0                        │B.        │  bits_per_sample: 16
0x14│   f0 00 d0 ee 40            │ ....@    │  total_samples_in_stream: 13692480
0x14│                  fd fd 1c 53│      ...S│  md5: "fdfd1c5314bbfe1a8adf8b0b96683bba" (raw bits)
0x1e│14 bb fe 1a 8a df 8b 0b 96 68│.........h│
0x28│3b ba                        │;.        │
    │00 01 02 03 04 05 06 07 08 09│0123456789│.metadatablocks[1]{}: (flac_metadatablock)
0x28│      84                     │  .       │  last_block: true
0x28│      84                     │  .       │  type: "vorbis_comment" (4)
0x28│         00 00 b9            │   ...    │  length: 185
    │                             │          │  comment{}: (vorbis_comment)
0x28│                  00 00 00 00│      ....│    vendor_length: 0
    │                             │          │    vendor: ""
0x32│05 00 00 00                  │....      │    user_comment_list_length: 5
    │                             │          │    user_comments[0:5]:
    │                             │          │      [0]{}:
0x32│            26 00 00 00      │    &...  │        length: 38
0x32│                        43 4f│        CO│        comment: "COPYRIGHT=Switch Plus (c) NCH Software"
0x3c│50 59 52 49 47 48 54 3d 53 77│PYRIGHT=Sw│
0x46│69 74 63 68 20 50 6c 75 73 20│itch Plus │
0x50│28 63 29 20 4e 43 48 20 53 6f│(c) NCH So│
0x5a│66 74 77 61 72 65            │ftware    │
    │                             │          │      [1]{}:
0x5a│                  26 00 00 00│      &...│        length: 38
0x64│45 4e 43 4f 44 45 44 42 59 3d│ENCODEDBY=│        comment: "ENCODEDBY=Switch Plus (c) NCH Software"
0x6e│53 77 69 74 63 68 20 50 6c 75│Switch Plu│
0x78│73 20 28 63 29 20 4e 43 48 20│s (c) NCH │
0x82│53 6f 66 74 77 61 72 65      │Software  │
    │                             │          │      [2]{}:
0x82│                        06 00│        ..│        length: 6
0x8c│00 00                        │..        │
0x8c│      47 45 4e 52 45 3d      │  GENRE=  │        comment: "GENRE="
    │                             │          │      [3]{}:
0x8c│                        26 00│        &.│        length: 38
0x96│00 00                        │..        │
0x96│      50 55 42 4c 49 53 48 45│  PUBLISHE│        comment: "PUBLISHER=Switch Plus (c) NCH Software"
0xa0│52 3d 53 77 69 74 63 68 20 50│R=Switch P│
0xaa│6c 75 73 20 28 63 29 20 4e 43│lus (c) NC│
0xb4│48 20 53 6f 66 74 77 61 72 65│H Software│
    │                             │          │      [4]{}:
... <some metadata redacted> ...
*   │until 0xe6.7 (37)            │          │

# display frame number for frames 252-259 and 2045-2050
flac> (.frames[252:260][], .frames[2045:2051][]).header.end_of_header | d
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[252].header.end_of_header{}:
0x2ed808│                     c3 bc   │       .. │  frame_number: 252
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[253].header.end_of_header{}:
0x2f0152│                  c3 bd      │      ..  │  frame_number: 253
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[254].header.end_of_header{}:
0x2f36fe│            c3 be            │    ..    │  frame_number: 254
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[255].header.end_of_header{}:
0x2f662e│c3 bf                        │..        │  frame_number: 255
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[256].header.end_of_header{}:
0x2f9270│         c0 80               │   ..     │  frame_number: 0
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[257].header.end_of_header{}:
0x2fbb2e│                  c0 81      │      ..  │  frame_number: 1
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[258].header.end_of_header{}:
0x2fe96e│         c0 82               │   ..     │  frame_number: 2
        │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[259].header.end_of_header{}:
0x301cea│                     c0 83   │       .. │  frame_number: 3
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2045].header.end_of_header{}:
0x17f5ba6│   c3 bd                     │ ..       │  frame_number: 253
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2046].header.end_of_header{}:
0x17f8342│               c3 be         │     ..   │  frame_number: 254
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2047].header.end_of_header{}:
0x17faebc│                        c3 bf│        ..│  frame_number: 255
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2048].header.end_of_header{}:
0x17fdd38│                  e0 a0 80   │      ... │  frame_number: 2048
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2049].header.end_of_header{}:
0x18009ac│                           e0│         .│  frame_number: 2049
0x18009b6│a0 81                        │..        │
         │00 01 02 03 04 05 06 07 08 09│0123456789│.frames[2050].header.end_of_header{}:
0x1804034│                        e0 a0│        ..│  frame_number: 2050
0x180403e│82                           │.         │

# collect all frame number deltas that are not 1
flac> [.frames[].header.end_of_header.frame_number] | delta | map(select(. != 1))
[
  -255,
  -255,
  -255,
  -255,
  -255,
  -255,
  -255,
  1793
]
```

```
$ flac -f -F -d -o <redacted>.flac.xiph.wav <redacted>.flac

flac 1.3.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

<redacted>.flac: ERROR, MD5 signature mismatch
$ ffmpeg -y -i <redacted>.flac <redacted>.flac.ffmpeg.wav
Input #0, flac, from '<redacted>.flac':
  Metadata:
    COPYRIGHT       : Switch Plus (c) NCH Software
    ENCODEDBY       : Switch Plus (c) NCH Software
    PUBLISHER       : Switch Plus (c) NCH Software
    TITLE           : <redacted>
  Duration: 00:05:10.49, start: 0.000000, bitrate: 1057 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '<redacted>.flac.ffmpeg.wav':
  Metadata:
    ICOP            : Switch Plus (c) NCH Software
    ENCODEDBY       : Switch Plus (c) NCH Software
    PUBLISHER       : Switch Plus (c) NCH Software
    INAM            : <redacted>
    ISFT            : Lavf58.76.100
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc58.134.100 pcm_s16le
[wav @ 0x7fcfa861a800] Non-monotonous DTS in output stream 0:0; previous: 1028096, current: 4096; changing to 1028096. This may result in incorrect timestamps in the output file.
[wav @ 0x7fcfa861a800] Non-monotonous DTS in output stream 0:0; previous: 1028096, current: 0; changing to 1028096. This may result in incorrect timestamps in the output file.
[wav @ 0x7fcfa861a800] Non-monotonous DTS in output stream 0:0; previous: 1028096, current: 4096; changing to 1028096. This may result in incorrect timestamps in the output file.
[wav @ 0x7fcfa861a800] Non-monotonous DTS in output stream 0:0; previous: 1028096, current: 8192; changing to 1028096. This may result in incorrect timestamps in the output file.
... <lots of similar logs removed>
size=   53104kB time=00:05:10.59 bitrate=1400.7kbits/s speed= 137x
video:0kB audio:53104kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000287%

$ ffmpeg -v verbose -i <redacted>.flac.xiph.wav -f null - 2>&1 | grep "frames encoded"
  Output stream #0:0 (audio): 13372 frames encoded (13692480 samples); 13372 packets muxed (54769920 bytes);
$ ffmpeg -v verbose -i <redacted>.flac.ffmpeg.wav -f null - 2>&1 | grep "frames encoded"
  Output stream #0:0 (audio): 13276 frames encoded (13594624 samples); 13276 packets muxed (54378496 bytes);
```

**Comment by ktmf01** [comment]
>     * In frame 0 to 2048 the frame number 256 resets back 0
> 
>     * At frame 2048 the resetting stops and goes from 255 to 2048 and after that seems normal
> 
> 
> I can't find anything in the FLAC specification how this should be handled.

This is obviously wrong. Do you think a note should be added to the spec that frame number MUST be equal to the number of frames in the stream that precede the current frame and the sample number MUST be equal to the number of interchannel samples that precede the current frame? Seems a little pedantic to me.

> The xiph decoder seems to ignore the resets and decodes all the samples. 

Yes, it doesn't check the frame number because it doesn't need it on linear decoding, as processing is linear. However, when libFLAC is asked to seek in such a file, it will surely fail. There is no way to properly seek in such a file except for fully decoding it first.

I'd say the spec shouldn't prescribe decoder behaviour for such files. libFLAC ignores this problem on a linear decode, which makes it able to re-encode such an invalid file to a valid one. However, it seems to me this cannot be expected from all decoders, especially not from decoders like ffmpeg which handles many different formats and takes another (less linear) decoding approach in favour of sharing as much code between codecs as possible. One could argue the `flac` command line tool could be a little more pedantic and output some warning messages, but not every decoder has the possibility to let the user know what is wrong.

Much like it is up to the decoder to support certain aspects and features of the format (even libFLAC lacks support for a lot of possibilities of the Ogg format has for example), I'd say handling error or invalid input is up the decoder. The only thing in this regard are the security considerations.

**Comment by wader** [comment]
> This is obviously wrong. Do you think a note should be added to the spec that frame number MUST be equal to the number of frames in the stream that precede the current frame and the sample number MUST be equal to the number of interchannel samples that precede the current frame? ~Seems a little pedantic to me.~ Perhaps not a bad idea, especially the 'interchannel samples' part, that might not be obvious.

First thanks for the detailed answer.

You mean add note about MUSTs for a stream that is suppose to support seeking and if seeking is not needed what can or should be ignored by a decoder?

I don't know how much flac is used in live streaming but then i guess discontinuities are inevitable?

I've seen many strange FLAC files but this is the first time i've seen this so i think it's very rare. Still wonder how they were produced. Was the timestamps weird even in the source files used somehow? and why all weird in the same way?

> > The xiph decoder seems to ignore the resets and decodes all the samples.
> 
> Yes, it doesn't check the frame number because it doesn't need it on linear decoding, as processing is linear. However, when libFLAC is asked to seek in such a file, it will surely fail. There is no way to properly seek in such a file except for fully decoding it first.

As i understand it even with proper sample/frame number seeking in a raw flac stream is up to lots of heuristics?

> I'd say the spec shouldn't prescribe decoder behaviour for such files. libFLAC ignores this problem on a linear decode, which makes it able to re-encode such an invalid file to a valid one. However, it seems to me this cannot be expected from all decoders, especially not from decoders like ffmpeg which handles many different formats and takes another (less linear) decoding approach in favour of sharing as much code between codecs as possible. One could argue the `flac` command line tool could be a little more pedantic and output some warning messages, but not every decoder has the possibility to let the user know what is wrong.
> 
> Much like it is up to the decoder to support certain aspects and features of the format (even libFLAC lacks support for a lot of possibilities of the Ogg format has for example), I'd say handling error or invalid input is up the decoder. The only thing in this regard are the security considerations.

A warning would be nice if possible but i think you know best, sounds like it's not much to do? as for the specification i personally like specifications that even state obvious things, maybe a good judgement call is if someone has asked a question about it? :)

**Comment by wader** [comment]
Was thinking about possible thing to add to the specifications a bit more. With "obvious things" i think i mean more comments or discussions about what decisions an implementing might face.

**Comment by ktmf01** [comment]
Whoops, I edited your comment where I meant to quote. I hope I restored it properly. Anyway:

> You mean add note about MUSTs for a stream that is suppose to support seeking and if seeking is not needed what can or should be ignored by a decoder?

I mean add a note that the frame number in a FLAC stream must be equal to the number of frames preceding the current frame in a stream. That means streams that do not conform to that are invalid. What a decoder does with such a stream is unspecified.

> I don't know how much flac is used in live streaming but then i guess discontinuities are inevitable?

I know FLAC is occasionally used in streaming. I don't know how clients handle an interrupted stream, but I guess the decoder has to be reset on a missing packet. 

> As i understand it even with proper sample/frame number seeking in a raw flac stream is up to lots of heuristics?

Seeking in FLAC is simply put:
1. guess where in the file the frame might be, go to that point in the file
2. try to find a valid frame (how much is validated is up to the decoder)
3. repeat if right frame is not found

If a valid frame is found with the wrong frame number, the decoder doesn't know where to try next, and can't be sure whether the sample that is sought is in the current frame or not.

> A warning would be nice if possible but i think you know best, sounds like it's not much to do?

Not for command line tools, but this is not something embedded devices can do.

**Comment by wader** [comment]
> > As i understand it even with proper sample/frame number seeking in a raw flac stream is up to lots of heuristics?
> 
> Seeking in FLAC is simply put:
> 
> 1. guess where in the file the frame might be, go to that point in the file
> 2. try to find a valid frame (how much is validated is up to the decoder)
> 3. repeat if right frame is not found
> 
> If a valid frame is found with the wrong frame number, the decoder doesn't know where to try next, and can't be sure whether the sample that is sought is in the current frame or not.

Ok thanks, good summary. Not sure if you have looked at the heuristics ffmpeg uses for FLAC, i've sent some changes to improve it but i have kind of run out of ideas at this point how to make less likely to find false frames.
