### ISSUE TITLE
Limits of the PICTURE block

### ISSUE THREAD

**Issue by phschafft** [ietf-wg-cellar/flac-specification#159]
Quoting from the current flac.md:
> Note that while the length fields for MIME type, description and picture data are 4 bytes in length and could in theory code for a size up > to 4 GiB, the total metadata block size cannot exceed what can be described by the metadata block header, i.e. 16 MiB.

Based on discussions on IRC on security considerations for decoding I would suggest to "soft" limit the length of both fields as per specs. By "soft" limit I mean a clarification like "encoders SHOULD NOT generate" and "decoders MAY consider invalid" if the lengths are not within limitations. I would also like to remind everyone that a flac picture block is also used in other standards such as embedded in Vorbis Comments (e.g. for Opus) and even in ID3 (APIC frame). The 16MB limitation may/does not apply there.

I suggest to define the "soft" limit not too small but within what is considered small for modern memory management. E.g. a value of 1^(12..16)-1 bytes would work fine here and should not create any real world limitation but helping against possible attacks.

**Comment by ktmf01** [comment]
> I would also like to remind everyone that a flac picture block is also used in other standards such as embedded in Vorbis Comments (e.g. for Opus) and even in ID3 (APIC frame). The 16MB limitation may/does not apply there.

Are you sure Opus refers to the FLAC specification for this? ID3 doesn't, the APIC frame is actually the inspiration for the FLAC picture metadata block structure, so it is actually the other way around. The fact that both share many similarities does not mean that limits in one apply to the other.

> I suggest to define the "soft" limit not too small but within what is considered small for modern memory management. E.g. a value of 1^(12..16)-1 bytes would work fine here and should not create any real world limitation but helping against possible attacks.

This would invalidate the majority of FLAC files with embedded album art. 2^16 byte is 65KiB which isn't sufficient for image files. From FLAC files I've bought from online stores, embedded album art files are often between 100KB and 2MB in size.

**Comment by phschafft** [comment]
> > I would also like to remind everyone that a flac picture block is also used in other standards such as embedded in Vorbis Comments (e.g. for Opus) and even in ID3 (APIC frame). The 16MB limitation may/does not apply there.
> 
> Are you sure Opus refers to the FLAC specification for this?

I'm not aware of a formal specification. However comments with the key "METADATA_BLOCK_PICTURE" containing a base64 encoded picture block are well supported (e.g. opusenc) and are something found in the wild. I'm also very sure I have seen that in Ogg/Vorbis streams as well.

> ID3 doesn't, the APIC frame is actually the inspiration for the FLAC picture metadata block structure, so it is actually the other way around.

I wonder were ID 17 (A bright coloured fish) then came from.

> The fact that both share many similarities does not mean that limits in one apply to the other.

That surely is true. However I still feel like the FLAC specs is one of the central definitions here and other would follow if there are such slight corrections.

> > I suggest to define the "soft" limit not too small but within what is considered small for modern memory management. E.g. a value of 1^(12..16)-1 bytes would work fine here and should not create any real world limitation but helping against possible attacks.
> 
> This would invalidate the majority of FLAC files with embedded album art. 2^16 byte is 65KiB which isn't sufficient for image files. From FLAC files I've bought from online stores, embedded album art files are often between 100KB and 2MB in size.

Maybe I didn't word my request here as clear as I thought. I was *not* talking about the blob part *only* about the media type ("MIME type") and description string.

**Comment by ktmf01** [comment]
> I'm not aware of a formal specification. However comments with the key "METADATA_BLOCK_PICTURE" containing a base64 encoded picture block are well supported (e.g. opusenc) and are something found in the wild. I'm also very sure I have seen that in Ogg/Vorbis streams as well.

I'm unfamiliar with the Vorbis/Opus way of doing things, but reading this it seems very different from how FLAC does things. In FLAC this picture is not a vorbis comment field, and it is not base64 encoded.

> I wonder were ID 17 (A bright coloured fish) then came from.

I've been wondering the same thing, but the ID3v2 spec precedes the introduction of a picture metadata block in FLAC by 8 years, and [the original specification document](https://xiph.org/flac/format.html#format_overview) specifically states `The picture format is similar to the [APIC frame in ID3v2](http://www.id3.org/id3v2.4.0-frames).`

> Maybe I didn't word my request here as clear as I thought. I was _not_ talking about the blob part _only_ about the media type ("MIME type") and description string.

MIME types are limited by RFC4288 to 255 characters in length, that limit could be added to the specification. As for the description, it seems reasonable to impose a limit, or just suggest one for decoders. Adding a limit for the description seems reasonable, however this should not lead to implementations skipping the overall length check, that remains important anyway.

**Comment by phschafft** [comment]
> > I'm not aware of a formal specification. However comments with the key "METADATA_BLOCK_PICTURE" containing a base64 encoded picture block are well supported (e.g. opusenc) and are something found in the wild. I'm also very sure I have seen that in Ogg/Vorbis streams as well.
> 
> I'm unfamiliar with the Vorbis/Opus way of doing things, but reading this it seems very different from how FLAC does things. In FLAC this picture is not a vorbis comment field, and it is not base64 encoded.

Correct. Vorbis and Opus does not have such a thing like a picture header therefore they just use the one from the FLAC specs in this base64 encoding. It's kind of a workaround. But it also means that it can handle much larger blocks (single comments can be up to 2^32-1 bytes long (even with keyname and base64 overhead that is still more than 16MB)).


> > I wonder were ID 17 (A bright coloured fish) then came from.
> 
> I've been wondering the same thing, but the ID3v2 spec precedes the introduction of a picture metadata block in FLAC by 8 years, and [the original specification document](https://xiph.org/flac/format.html#format_overview) specifically states `The picture format is similar to the [APIC frame in ID3v2](http://www.id3.org/id3v2.4.0-frames).`

You always learn something new. Thank you. :)

> > Maybe I didn't word my request here as clear as I thought. I was _not_ talking about the blob part _only_ about the media type ("MIME type") and description string.
> 
> MIME types are limited by RFC4288 to 255 characters in length, that limit could be added to the specification.

I was never fully sure if the media type given here is allowed to include parameters and how long they might be. That is why I suggested a bit more just to be on the safe side and also so the same limit can be used for the description as well (helping implementations as they can use the same code for both without the need for another parameter).

However as said it makes most sense to me to write this in a way that allows the decoder to consider them invalid if they exceed the limit yet not requiring them (keeping it compatible with the current spec) would still allow implementations doing that even if one field is more limited than the other one.

> As for the description, it seems reasonable to impose a limit, or just suggest one for decoders. Adding a limit for the description seems reasonable, however this should not lead to implementations skipping the overall length check, that remains important anyway.

Yes, I'm fully with you here. This is about an additional check, not to replace the fundamental one.
