### ISSUE TITLE
Adding email address for CELLAR working group in IANA section

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-cellar/flac-specification#211]
I just noticed that -08 says 

   Person **& email address** to contact for further information: IETF CELLAR WG 

where it should say 

   Person & email address to contact for further information: IETF CELLAR WG <cellar@ietf.org>

I can't believe I didn't notice this! :upside_down_face:

There is no rush to produce a fix for this - we can batch it with anything else we get back from AD review - but I didn't want to forget completely.

**Comment by ktmf01** [comment]
I actually copied this from the Matroska draft, which has the same issue thrice. Should it be added there as well?

**Comment by robUx4** [comment]
Like this ? https://github.com/ietf-wg-cellar/matroska-specification/pull/750
