### ISSUE TITLE
Should we move stuff to IETF wiki

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#226]
From https://mailarchive.ietf.org/arch/msg/cellar/1hKWAbLAq9UrmV1Mb25QkM0j3Ug/

>> In Section 12, there's a reference to a github link.  I'm not sure how this will be received by the RFC Editor or the IESG.  What guarantees are there that this link is permanent?  This goes for other github links, e.g., in Section 10.3.
>
> Considering the other github links, the working group considered github a more stable resource than IETF's trac. If I recall correctly the IETF wiki wasn't ready when these parts were prepared. Do you think we should move these resources to the IETF wiki?
>
> Considering the github link in section 12 (which I don't think we can move to the wiki), the working group considered these permanent. Does the IETF provide for storing a collection of large files somewhere permanent, so these files can be transferred there? Perhaps the link should go to an IETF wiki page that points to the github so the link can be updated if necessary?

Should we move the github wiki stuff to the IETF wiki? And what about https://github.com/ietf-wg-cellar/flac-test-files

**Comment by mcr** [comment]
We can certainly move things into the wiki, and I've asked the RPC about this.

**Comment by mcr** [comment]
Response from RPC says:

https://www.rfc-editor.org/styleguide/part2/#ref_repo

that we can reference github for our files.
