### ISSUE TITLE
Questions on SHOULDs in document

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#227]
From https://mailarchive.ietf.org/arch/msg/cellar/1hKWAbLAq9UrmV1Mb25QkM0j3Ug/

>>  Regarding the SHOULD in Section 5, I'd like to know why there's an option here.  What effect is there on interoperability if an implementation chooses not to do what's described there?  I have the same question about the RECOMMENDED in Section 8.2, the RECOMMENDED in Section 8.6.2, the SHOULD in Section 8.7, the RECOMMENDED and SHOULD NOT in 8.7.1, and the SHOULD in 12.
>
> Section 5: the reason for this SHOULD is explained in that paragraph, but perhaps it isn't clear enough? Can you point me to the ambiguity? I'll paraphrase: unsigned samples can be represented in signed samples in several ways. As the coding tools provided by the FLAC format work best with samples centered around zero (i.e. the highest compression is reached), it is recommended to convert unsigned samples to signed samples by subtracting half the range, if that indeed results in samples being centered around zero. There is no interoperability concern when choosing another method to convert unsigned samples to signed samples, it just doesn't compress as good.
> 
> Section 8.2: here I also do not understand the ambiguity, can you point me to it? I'll paraphrase: FLAC is designed for audio, which has a sample rate, otherwise it is no audio. If someone chooses to store something in FLAC without a samplerate (i.e. something that is not audio), it is recommended to add some metadata on what the data is. As I do not know of these non-audio uses, the document cannot specify a format for this metadata, so I can only recommend it, not enforce it.
> 
> Section 8.6.2 is pretty much the same as 8.2, paraphrasing: if audio is stored of which the specifics cannot be formally described in the FLAC format, please store it informally in some way. This is deliberately "open-ended". I'm unsure how to clarify this.
> 
> Section 8.7: it says the bits have no meaning in a particular context. I don't think the document should enforce these bits to be zero when they have no meaning: a decoder should ignore these bits, not throw an error when they are not zero.
> 
> Section 8.7.1: the numbers should start with 1 and increase sequentially because that makes sense to users. However, I think a parser should still accept a cuesheet where this is not the case. This is because I know some musicians have used cuesheet track numbers for artistic purposes in the past, see for example: https://en.wikipedia.org/wiki/Hidden_track Or see for example the album Follow the Leader by KoЯn, which starts on track 13. Should I further clarify this?
> 
> Section 12: The document says one SHOULD do something, except in certain circumstances. If I change that to MUST, it doesn't work I think? Can a MUST statement have exceptions written like this?

As said, I don't know what is unclear here.

**Comment by mcr** [comment]
It's not that it is unclear, the question that arises for "SHOULD" is that SHOULD implies an exception.  The exception needs to be documented, otherwise it's a MUST.  That often feels too harsh, particular for non-english speakers, but that's BCP14 for you.

   If that is the case, all
   sample representations SHOULD be converted by first copying the
   number to a signed integer with sufficient range and then subtracting
   half of the range of the unsigned integer type, which should result
   in a signal with samples centered around 0.
   .. implementations which do NOT copy the number to a signed integer will cause... THE UNIVERSE TO EXPLODE?

**Comment by ktmf01** [comment]
My point is that none of these SHOULD and RECOMMENDED can be MUST, and the reason why was clear from the context. Rereading it, I guess it probably isn't too clear.

I'll rephrase, avoiding BCP14 terms. For example
```diff
-There are several ways to convert unsigned sample representations to signed sample representations, but the coding methods provided by the FLAC format work best on audio signals of which the numerical values of the samples are centered around zero, i.e. have no DC offset. In most unsigned audio formats, signals are centered around halfway the range of the unsigned integer type used. If that is the case, all sample representations SHOULD be converted by first copying the number to a signed integer with sufficient range and then subtracting half of the range of the unsigned integer type, which should result in a signal with samples centered around 0.
+There are several ways to convert unsigned sample representations to signed sample representations, but the coding methods provided by the FLAC format work best on audio signals of which the numerical values of the samples are centered around zero, i.e. have no DC offset. In most unsigned audio formats, signals are centered around halfway the range of the unsigned integer type used. If that is the case, converting sample representations by first copying the number to a signed integer with sufficient range and then subtracting half of the range of the unsigned integer type results in a signal with samples centered around 0.
```

**Comment by H2Swine** [comment]
Concerning the signed/unsigned discussion in section 5: 
Is it completely unambiguous how to encode/decode unsigned signals? I sense that the wording tries to address it, but if it is not unambiguous, is then the process lossless?
Sure, the reference implementation has done that thing since forever, and since it defaults to decoding to WAVE, the 8-bit signals will then get 128 added and ... but is the _specification_ clear enough about what this sixteen-sample signal really is? 
81, 82, 83, ..., 95, 96.

It so happens that every sample is in the range 0 to 127, and most 8-bit signals are not. But, is it clear what flac -d thisfile.flac should decode that to, as per the specification?

**Comment by H2Swine** [comment]
Oh sorry, should evidently have posted before breakfast ...

**Comment by ktmf01** [comment]
> Is it completely unambiguous how to encode/decode unsigned signals? I sense that the wording tries to address it, but if it is not unambiguous, is then the process lossless?

No, it is not. In fact, it is intentionally ambiguous. FLAC stores signed signals only, and how to convert unsigned signals is up to the user. For audio, it does not matter, DC isn't rendered anyway. After all, this document is specifying the FLAC format, not the conversion process from WAV to FLAC.

For WAV and AIFF, the conversion between 8-bit signed and 8-bit unsigned is only possible in one way without wrapping: 'Connect' the lowest possible value in both formats and 'connect' all other value consecutively. There is however no reason to assume another format could not work differently.

However, if someone wants to store 8-bit unsigned signals in 9-bit (or more) signed samples by simply using the zero and positive values only, that is still possible. That doesn't really make sense for audio, but I see no reason to disallow it.
