### ISSUE TITLE
Channel mask only in Vorbis comments, or define a different metadata type for it?

### ISSUE THREAD

**Issue by H2Swine** [ietf-wg-cellar/flac-specification#238]
I [raised this question over at Hydrogenaud.io](https://hydrogenaud.io/index.php/topic,124983) , and it was pointed out that [the question of where had been only briefly up some ten years ago.](http://lists.xiph.org/pipermail/flac-dev/2013-January/003582.html) 
Then speak of the Devil: a couple of weeks later, it comes up just here in the recent pull requests (#237 also) on how to standardize the channel mask Vorbis comment. Which is the reason I raise the issue here and not over at github.com/xiph/flac 

Since the discussion on the formal specification of channel mask handling is still then not completely done, it looks natural to take the question up here and now: _would it not be beneficial to define a different BLOCK_TYPE for channel allocation_?  (Likely "in addition" to the Vorbis comment, although it breaks the free-form modus operandi - because some applications already have started supporting it as a tag.)

However, keeping it in a tags section only, leaves it vulnerable to the whims of tagging applications.  Even something as FLAC-friendly as foobar2000 had that problem as recent as 2021. And to quote the dev's response in https://hydrogenaud.io/index.php/topic,120954.0.html , _"Removal of tags should not alter decoding output"_ - true, but less aware applications will presumably do precisely that, which makes a case to put it somewhere where taggers won't nuke it.

Possible solutions then? 

* A new BLOCK_TYPE.  FLAC isn't much at risk of running out of block types.  Make it contain precisely byte by byte the same as now proposed in a Vorbis comment, and prescribe: SHOULD appear both there and in Vorbis comment for compatibility, decoder SHOULD honour it if it only appears in one of them, and maybe a recommendation for the cases they both are present but disagree. 

I twisted my head to come up with good arguments against this.  I might have found one, namely that some applications that can convert .flac to .flac with tags transfer, may fail to transfer this block type.  But if there is a SHOULD be both places, then ... not much _new_ harm introduced.

* An alternative: Since FLAC now is about to document also the foreign metadata APPLICATION blocks, it could be an alternative to put it there instead?  Unless decoders are well justified in skipping _all_ APPLICATION block types for playback purposes, then it is a bad idea to force decoders identify them all to honour only one. On the other han I guess that using APPLICATION leaves less chances that an ill-written player will crash (one that knows to ignore APPLICATION but not how to ignore an unknown block type) - although I am not sure if it is a bad thing that a player that cannot play the thing right, errs out. 

The latter argument also speaks in favour of something that breaks compatibility altogether for the files in question, as proposed by someone else in the hydrogenaud.io thread - I mention it without going further into that discussion.

**Comment by ktmf01** [comment]
> Since the discussion on the formal specification of channel mask handling is still then not completely done

I'm not sure what you're referring to here. As far as I know there is no recent discussion on the channel mask part of the spec.

The spec has progressed too far in the IETF process to make big changes like these without a very good reason. I don't see that very good reason. This behaviour has been around for 17 years already (see https://github.com/xiph/flac/commit/cc5c1d8837185ac60630fd8cc78cf1585fa84720) Probably using a tag wasn't the best way to do this, but I think it is now too late to change it, not just because of the state of the spec in the IETF process, but in general.

**Comment by H2Swine** [comment]
Well not so fast - although it is my bad, in a way: Even if it has behaved this way for years, the IETF document does indeed prescribe something "new" to it when the channel allocations are non-standard, which are pointed to Application, 8.6.2 last sentence.  Reading 8.4 that it doesn't forbid this nor that, it seems the answer actually is _"If a Vorbis comment isn't good enough for you, then go ahead register an Application block - you're on your own of course"_ 
Similar for content when sample rate is set to 0 in Streaminfo, 8.2, then it is recommended (not using caps - deliberate?) to use a Vorbis field or an application metadata block.

Although then, I don't know whether the document is clear enough what metadata a decoder MUST/SHOULD honour, especially when it can read Application and encounters one it does not understand: it could affect playback, _at least_ if sample rate or WAVEFORMATEXTENSIBLE tag is declared as zero.  Are they permitted to just skip?  SHOULD they skip, if WAVEFORMATEXTENSIBLE equals zero and they cannot read the Application block? 

(It likely makes sense to consider whether a decoder may honour _unregistered_ Application blocks - i.e. maybe put a MUST or SHOULD also in the first line of Table 5 in 8.4. I don't know whether it is clear enough as is in the document. 
To be clear, both this and the previous "I don't know whether" are literally an "I don't know", it might be that there is an agreed-upon answer and the issue could be closed. 
Uh, and 8.4 makes reference flac.exe a "third-party" application :-)  That is not making any confusion though.)

**Comment by ktmf01** [comment]
> Well not so fast

I fail to see how this comment relates to the original issue.

As we know, FLAC is being used for way more things than music playback. That last sentence of 8.6.2 was specifically added for decoding ambisonics, which is complicated enough that it would warrant its own RFC. Other uses like multitrack recordings or non-audio signals to name a few, are too diverse to put MUST and MUST NOT stuff around. I simply cannot comprehend all possible use cases.

So, if you use FLAC for music in common formats, than this document is clear enough I think. If you use it for ambisonics, there is a need for additional specification, which the working group cannot provide at this time. If you use it for recordings or measurements, the specification leaves a lot of stuff open, but you probably shouldn't try to play those back in a regular playback application anyway and expect it to work correctly.
