### ISSUE TITLE
range of wasted bits

### ISSUE THREAD

**Issue by AnterCreeper** [ietf-wg-cellar/flac-specification#239]
is the max wasted bits the sample depth?

**Comment by ktmf01** [comment]
See https://www.ietf.org/archive/id/draft-ietf-cellar-flac-12.html#name-format-principles

> When a FLAC file contains data that is forbidden or otherwise not valid, decoder behavior is left unspecified. A decoder MAY > choose to stop decoding upon encountering such data. Examples of such data are
(...)
> - The number of wasted bits (see [Section 9.2.2](https://www.ietf.org/archive/id/draft-ietf-cellar-flac-12.html#wasted-bits-per-sample)) used by a subframe is such that the bit depth of that subframe (see [Section 9.2.3](https://www.ietf.org/archive/id/draft-ietf-cellar-flac-12.html#constant-subframe) for a description of subframe bit depth) equals zero or is negative.

**Comment by AnterCreeper** [comment]
pretty thanks! reply so fast!
