### ISSUE TITLE
anchors in markdown

### ISSUE THREAD

**Issue by privatezero** [ietf-wg-cellar/flac-specification#25]
Currently anchors linking to section headers with underscores in them (such as FRAME_HEADER) are broken in markdown.

The current anchors do, however, create working internal links in the html generated by the makefile.

**Comment by dericed** [comment]
Ya I found that same and tried. I started a few new section headers in my last PR and dropped the underscores for the same reason.

**Comment by dericed** [comment]
Related issue in pandoc as well https://github.com/lierdakil/pandoc-crossref/issues/66. Should consider switching to spaces or hypens.

**Comment by ablwr** [comment]
Are the underscores significant as descriptors?

**Comment by privatezero** [comment]
This is the response that this issue received on flac-dev. (Addresses why they are that way and makes a suggestion for updating)

http://lists.xiph.org/pipermail/flac-dev/2017-June/006289.html

**Comment by ablwr** [comment]
Oooooooh an interesting adventure!

**Comment by dericed** [comment]
Using the current names from the source code seems worthwhile as it may make the document more reviewable to communities that support its libraries, but this doesn't resolve the initial issue. Perhaps there is a way to get underscores to work in section names (escaping?), otherwise perhaps we can somehow avoid naming sections are the literal names.

**Comment by ablwr** [comment]
I was just thinking the same... and, considering this is trouble not just for Markdown but also downstream/upstream for Pandoc, the headers can be in a "human readable" format and then all other references within can use the accurate names as in source. This should all be weighted on the linking that will occur when building the RFC... if I get some time, and I am pretty sure I will have some soon, I will test around with this and see if we can come up with a winning solution!

**Comment by dericed** [comment]
Is pandoc used here, I think it is just markdown -> mmark -> xml2rfc. I suppose having the section name be the name from code without the underscores may be ok.

**Comment by dericed** [comment]
Perhaps worthwhile to comment on the thread @privatezero mentioned before starting as it's likely a lot of work with cross referencing back to the code.

**Comment by ablwr** [comment]
Oh, that's better. I assumed Pandoc would get its greedy hands in here somewhere, somehow.

**Comment by ablwr** [comment]
> Perhaps worthwhile to comment on the thread @privatezero mentioned before starting as it's likely a lot of work with cross referencing back to the code.

Yeah those are separate issues and worth separate tickets, I think.

**Comment by dericed** [comment]
For cellar associated repositories, I think pandoc is only used in FFV1 to produce a non-RFC-style PDF with the equations in LaTeX.

**Comment by privatezero** [comment]
Regarding problems downstream with the RFC conversion - the last time I tested the links were working fine in current form with things like the html derived from the markdown. It was just the initial markdown that had issues.

**Comment by retokromer** [comment]
@privatezero Is this issue resolved?

**Comment by dericed** [comment]
@retokromer I don't think so

**Comment by privatezero** [comment]
@retokromer I will have to wait until next week when I get back from traveling to double check any details, but current status should be the same as before. Also, no changes have been made regarding cross-referencing the code for anchor names.

**Comment by retokromer** [comment]
@privatezero Thank you for the answer! Please take your time, it’s not an urgent matter on my side.
