### ISSUE TITLE
standardize expression of frame header

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/flac-specification#43]
Both `frame header` and `FRAME_HEADER` are used to reference the same concept. I propose standardizing these expressions, see the discussion at https://github.com/privatezero/flac_markdown/pull/35#issuecomment-304284069.

**Comment by privatezero** [comment]
@dericed I assume that this also calls for the standardization of expressions suffering from the same problem (i.e. subframe header vs SUBFRAME_HEADER?)

**Comment by retokromer** [comment]
Question: Are we still resolving formal issues or can we start to delve into the actual content?

**Comment by retokromer** [comment]
@dericed Is this issue resolved?

**Comment by dericed** [comment]
@retokromer I don't think so
