### ISSUE TITLE
Rename repo to flac-specification?

### ISSUE THREAD

**Issue by JeromeMartinez** [ietf-wg-cellar/flac-specification#79]
I suggest to "normalize" repo names, and I think that the way Matroska and EBML repos are named are easier for searches, so I suggest to rename "Cellar-FLAC" repo to "flac-specification".

**Comment by retokromer** [comment]
>I suggest to rename "Cellar-FLAC" repo to "flac-specification".

I second.

**Comment by retokromer** [comment]
ping

**Comment by JeromeMartinez** [comment]
@mcr for consideration :).

**Comment by mcr** [comment]
Done.
