### ISSUE TITLE
Missing specification of bits-per-sample adjustment for subframes

### ISSUE THREAD

**Issue by fweimer** [ietf-wg-cellar/flac-specification#83]
The reference implementation increases the number of bits per sample by one in the following cases:

* For the first subframe if the channel assignment is 0b1001.
* For the second subframe if the channel assignment is 0b1000 or 0b1010.

Not doing this results in an implementation which is not interoperable.

**Comment by fweimer** [comment]
Additionally, the number of bits per samples is *decreased* by the wasted-bits-per-sample amount.

**Comment by wader** [comment]
Is this same as #111 ?

**Comment by ktmf01** [comment]
This is fixed by #98 and will be further stressed if #120 is merged
