### ISSUE TITLE
Unclear license of this specification

### ISSUE THREAD

**Issue by fweimer** [ietf-wg-cellar/flac-specification#85]
The original HTML file claims it is licensed under the GNU Free Documentation License. I do not think this is something that will be acceptable to the IETF. Will the document be re-licensed under different terms? A liberal license that would permit reusing specification fragments in program code would be best (in other words, not the IETF default license).

**Comment by retokromer** [comment]
Thank you, @fweimer, for pointing it out! It was re-licensed with the agreement of the original author, Josh Coalson (see the Cellar mailing list).
