### ISSUE TITLE
Missing specification of wasted bits-per-sample value

### ISSUE THREAD

**Issue by fweimer** [ietf-wg-cellar/flac-specification#87]
It is not immediately obvious howwhen to apply the wasted bits-per-sample value during decoding. It's possible to guess that a left shift involved, but it is unclear whether this happens after or before LPC decoding. (The impact on the bits-per-sample value of the subframe is also unspecified, see #83.)

**Comment by ktmf01** [comment]
Fixed by #94

**Comment by H2Swine** [comment]
It is not obvious if there is any limitation to how many wasted bits can be specified - or more precisely, how many zeroes there could be following the wasted bits flag while still being a compliant stream. Say the subframe is 16 bits and the decoder reads the wasted bits flag and then a lot of zeroes signifying the number of bits wasted. Arguably a sane encoder wouldn't write seventeen zeroes, but what should the decoder do if it encounters it? Treat as 16 or err out? 

10.2.3 says "minus the number of wasted bits coded in the subframe header", so surely if the above is supposed to be valid, it must be "converted to 16 before subsection 10.2.3".

**Comment by ktmf01** [comment]
Well, I'd say if a subframe has 16 bits, there can be no more than 15 wasted bits, or there is nothing left. In general decoder behavior is left unspecified for malformed streams.

I suggest adding the following at the end of section 'Format principles'
> When a FLAC file contains invalid data, decoder behavior is left unspecified. A decoder MAY choose to stop decoding on encountering such invalid data. Examples of such invalid data are
> - One or more decoded sample values exceeds the range offered by the bit depth as coded for that frame. E.g. in a frame with a bit depth of 8 bits, any samples not in the inclusive range from -128 to 127 are invalid.
> - The number of wasted bits (see section [wasted bits per sample](wasted-bits-per-sample)) is equal to or exceeds the bit depth of that subframe (see section [constant subframe](#constant-subframe) for a description of subframe bit depth)
> - A frame header CRC (see section [frame header CRC](#frame-header-crc)) or frame footer CRC (see section [frame footer](#frame-footer)) indicates the decoded data is invalid
> - One of the invalid bit patterns described in table X above is used

The mentioned table is #202 by the way

**Comment by H2Swine** [comment]
I completely agree that wasted bits exceeding the bit depth is nonsense.  I am not so sure about the case where they are equal - given an all-zeroes subframe. Especially not if it is unclear whether current spec actually forbids it. 
Consider a subframe where all values are zero.  Encoder looks for "bits to be wasted" by counting trailing zeroes.  In this frame it finds, ah, 16 bits can be wasted.  And so let us encode it as CONSTANT using (as per 10.2.3) 16 - 16 = 0 bits.  Fine!  The value is unique and can be decoded. 
Is that outright forbidden as of current spec?  A new restriction requires some considerations pro et contra, and if the verdict is that it is already forbidden but not in a too clear language (don't take me as yardstick, I am rather asking a question too many) then maybe another "MUST" in 10.2.2 is appropriate.  

If there actually isn't anything forbidding it, then it is likely a matter for Appendix C.  


(By the way, when the text permits a decoder to abort or skip ... maybe it could be spent a few words that it is allowed to _mute_ at discretion, say if it has reason to believe anything about the duration of invalid (or not received timely enough for realtime playback) data?)

**Comment by ktmf01** [comment]
The problem here is that shifting a value by the width of its datatype (shifting a 32-bit int by 32 bit for example) is undefined behavior in C. Also, there really isn't anything left to describe. Both libFLAC and libavcodec specifically look out for this case and never use `wasted bits = bps` on encoding.

**Comment by H2Swine** [comment]
That calls for a "MUST be strictly smaller than" in 10.2.2 then?
