### ISSUE TITLE
Missing singedness indication

### ISSUE THREAD

**Issue by fweimer** [ietf-wg-cellar/flac-specification#90]
In the following places of the specification, signed values are used implicitly (the default are signed values):

* The constant value in `SUBFRAME_CONSTANT`.
* The warm-up samples in `SUBFRAME_FIXED`.
* The warm-up samples in `SUBFRAME_LPC`.
* The sample data in `SUBFRAME_VERBATIM`.
* The Golomb encoding (see [this comment](https://github.com/cellar-wg/Cellar-FLAC/issues/55#issuecomment-691470532)).

Except for the last item, these values are encoded as two's complement.

**Comment by ktmf01** [comment]
I believe #97 and #122 fix these 5 points
