### ISSUE TITLE
Unclear meaning of maximum frame size (with respect to reference implementation behavior)

### ISSUE THREAD

**Issue by fweimer** [ietf-wg-cellar/flac-specification#91]
The reference implementation produces frames that are larger than the maximum frame size in `METADATA_BLOCK_STREAMINFO` (even when the maximum frame size is not zero). I do not know if this a bug in the reference implementation, or if something is under-specified here.

**Comment by ktmf01** [comment]
Can you comment on this a little more? Do you remember how you found out this is wrong? Do you have an example?

**Comment by fweimer** [comment]
As far as I can tell now, it's a bug in `flac -a` output, not in the data stream. The generated streams are consistent. So this is not an issue relevant to the specification.

**Comment by ktmf01** [comment]
I noticed the `bits` output in the analysis file for the first frame includes the size of the metadata, is that what you refer to? Or did you find inconsistencies in other frames as well?
