### ISSUE TITLE
FLAC does not have a MIME type registered with IANA

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/flac-specification#99]
I believe the commonly used MIME type audio/flac has not been registered with IANA. Is this a potential problem in any way?

**Comment by JeromeMartinez** [comment]
True, it is not in the [MIME list](https://www.iana.org/assignments/media-types/media-types.xhtml).
This is part of the work of the group, we'll have to do this administrative work in order to have the RFC.

**Comment by mcr** [comment]
This document can register audio/flac in it's IANA Considerations.  You'll need the MIME media type template.
EBML and Matroska have examples, and/or see https://www.rfc-editor.org/rfc/rfc6838.html

**Comment by ktmf01** [comment]
I was under the impression that MIME type registration would be something necessary for the standard, but as I understand it now that it is actually the other way round. Correct? If that is the case, this issue can be closed.

**Comment by mcr** [comment]
> I was under the impression that MIME type registration would be something necessary for the standard, but as I understand it now it is actually the other way round. Correct? If that is the case, this issue can be closed.

There are many different allocation policies for IANA things.
MIME type registration can be done by expert review, or via an IETF document.    We don't have to do the registration before the document can be published, it's done during the publication process.   We can get the expert review now though, which effectively reserves it.

IANA and IETF and the RFC-editor communicate on an hourly basis :-)
